version: 2.1

# ================
# --- Workflow ---
# ================
workflows:
  version: 2
  main:
    jobs:
      - build

# ===============
# --- Aliases ---
# ===============
restore_yarn_cache: &restore_yarn_cache
  restore_cache:
    keys:
      - v1-dep-{{ .Branch }}-{{ .Revision }}
      - v1-dep-{{ .Branch }}-
      - v1-dep-

save_yarn_cache: &save_yarn_cache
  save_cache:
    key: v1-dep-{{ .Branch }}-{{ .Revision }}
    paths:
      - ~/.cache/yarn
      - ./node_modules

# ============
# --- Jobs ---
# ============
jobs:
  build:
    working_directory: ~/app
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: node:11-slim
    steps:
      # =====
      # Setup
      # =====
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - *restore_yarn_cache
      - run: npm install -g yarn
      - run: yarn install --silent --no-progress --frozen-lockfile
      - *save_yarn_cache
      # ====
      # Test
      # ====
      - run: yarn lint
      - run: yarn test:coverage
      # ========
      # Teardown
      # ========
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
